# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultant_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='consultant',
            unique_together=set([]),
        ),
    ]
